api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "coin-discount-v2"
type = "function"
uid = "417003d3-cbf6-6084-c716-4e0e85ba75cff9dbe057"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"